name: bookipedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.4.1
  pinput: ^4.0.0
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  custom_timer: ^0.2.3
  syncfusion_flutter_pdfviewer: ^25.1.42
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  gap: ^3.0.1
  http_parser: ^4.0.2
  animated_text_kit: ^4.2.2
  favicon: ^1.1.2
  webview_flutter: ^4.7.0
  selectable: ^0.3.1
  audioplayers: ^6.0.0
  another_flushbar: ^1.12.30
  transparent_image: ^2.0.1
  flutter_expandable_fab: ^2.1.0
  percent_indicator: ^4.2.3
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo-Final-No-Title.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
